export const Nigeria = [
  { code: '214', name: 'First City Monument Bank' },
  { code: '215', name: 'Unity Bank' },
  { code: '221', name: 'Stanbic IBTC Bank' },
  { code: '232', name: 'Sterling Bank' },
  { code: '301', name: 'JAIZ Bank' },
  { code: '304', name: 'Stanbic Mobile Money' },
  { code: '305', name: 'Paycom' },
  { code: '306', name: 'eTranzact' },
  { code: '307', name: 'Ecobank Mobile' },
  { code: '309', name: 'FBN Mobile' },
  { code: '311', name: 'parkway' },
  { code: '315', name: 'GTBank Mobile Money' },
  { code: '322', name: 'Zenith Mobile' },
  { code: '323', name: 'Access Mobile' },
  { code: '401', name: 'ASO Savings and & Loans' },
  { code: '070', name: 'Fidelity Bank' },
  { code: '030', name: 'Heritage' },
  { code: '076', name: 'Skye Bank' },
  { code: '032', name: 'Union Bank of Nigeria Plc' },
  { code: '033', name: 'United Bank for Africa' },
  { code: '035', name: 'Wema Bank' },
  { code: '084', name: 'Enterprise Bank' },
  { code: '044', name: 'Access Bank' },
  { code: '050', name: 'Ecobank Plc' },
  { code: '011', name: 'First Bank of Nigeria' },
  { code: '057', name: 'Zenith Bank' },
  { code: '058', name: 'GTBank Plc' },
  { code: '063', name: 'Diamond Bank' },
  { code: '068', name: 'Standard Chartered Bank' },
];
