# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - master

pool:
  vmImage: "ubuntu-latest"

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "12.x"
    displayName: "Install Node.js"

  - script: npm install yarn
    displayName: "Install yarn"

  - script: yarn
    displayName: "Install Dependencies"

  - script: yarn lint
    displayName: "Code Analysis"

  # - script: npx ng test --watch=false --codeCoverage=true
  #   displayName: 'Tests'

  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testResultsFormat: "JUnit"
      # Make sure you've changed testResultsFiles to the one below
      testResultsFiles: "**/TESTS-*.xml"
    displayName: "Publish Test Results"

  - task: PublishCodeCoverageResults@1
    condition: succeededOrFailed()
    inputs:
      codeCoverageTool: "Cobertura"
      summaryFileLocation: "$(Build.SourcesDirectory)/coverage/cobertura-coverage.xml"
    displayName: "Publish Code Coverage Results"

  - script: yarn build --prod
    displayName: "Build"

  - script: npm install firebase-tools
    displayName: "install firebase"

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: "dist/kobolet"
      ArtifactName: "web-app"
      publishLocation: "Container"
    displayName: "Publish Artifacts"
